---
- name: automating cronjob for a particular user on multiple managed nodes
  hosts: all
  tasks:
    - name: setting a cronjob that runs every 2 minutes and executes logger “EX294 in progress”
      cron:
        name: logger
        minute: "*/2"
        hour: "*"
        job: 'logger "Ex294 in progress"'
        user: username

