---
- name: Playbook for packages.yml
  hosts: all
  tasks:

    - name: installing the php and mariadb packages on dev,test,prod host groups.
      yum:
        name: 
          - php
          - mariadb
        state: present
      when: inventory_hostname in groups['dev'] or inventory_hostname in groups['test'] or inventory_hostname in groups['prod']

    - name: install the RPM development tool package group on dev hostgroup.
      yum:
        name: "@RPM Development tools"
        state: present
      when: inventory_hostname in groups['dev']

    - name: update all packages on dev hostgroup.
      yum:
        name: '*'
        state: latest
      when: inventory_hostname in groups['dev']
